{{- if and .Values.vaultAuth.serviceAccount.create .Values.node.blockProducer.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.vaultAuth.serviceAccount.name | quote }}
  labels:
    {{- include "cardano-node.labels" . | nindent 4 }}
{{- end }}
