{{- $fullName := include "cardano-node.fullname" . -}}
{{- $selectorLabels := include "cardano-node.selectorLabels" . -}}
{{- $serviceAccountName := include "cardano-node.serviceAccountName" . -}}
{{- $proxyConfigName := include "cardano-node.proxyConfigName" . -}}
{{- $configurationConfigMapName := include "cardano-node.configurationConfigMapName" . -}}
{{- $blockProducer := .Values.node.blockProducer | default dict -}}
{{- $hasBlockProducerSecret := and ($blockProducer.existingSecret) (ne ($blockProducer.existingSecret | trim) "") -}}
{{- $proxyChecksum := "" -}}
{{- if and .Values.proxy.enabled .Values.proxy.config.create }}
{{- $proxyChecksum = include (print $.Template.BasePath "/configmap-proxy.yaml") . | sha256sum -}}
{{- end }}
{{- $configurationChecksum := "" -}}
{{- if and .Values.configuration.create .Values.configuration.files }}
{{- $configurationChecksum = include (print $.Template.BasePath "/configmap-configuration.yaml") . | sha256sum -}}
{{- end }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "cardano-node.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.node.replicas | int }}
  selector:
    matchLabels:
{{- $selectorLabels | nindent 6 }}
  serviceName: {{ printf "%s-headless" $fullName }}
  template:
    metadata:
      labels:
{{- $selectorLabels | nindent 8 }}
      {{- $hasAnnotations := or .Values.podAnnotations (or $proxyChecksum $configurationChecksum) -}}
      {{- if $hasAnnotations }}
      annotations:
        {{- if $proxyChecksum }}
        checksum/proxy-config: {{ $proxyChecksum }}
        {{- end }}
        {{- if $configurationChecksum }}
        checksum/configuration: {{ $configurationChecksum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.node.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.node.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: cardano-node
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.node.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- $args := dict "all" (default (list) .Values.node.args) }}
          {{- if $hasBlockProducerSecret }}
          {{- $mountPath := default "/block-producer" $blockProducer.mountPath }}
          {{- $kesKeyFile := default "kes.skey" $blockProducer.kesKeyFile }}
          {{- $vrfKeyFile := default "vrf.skey" $blockProducer.vrfKeyFile }}
          {{- $opCertFile := default "op.cert" $blockProducer.operationalCertificateFile }}
          {{- $_ := set $args "all" (concat $args.all (list "--shelley-kes-key" (printf "%s/%s" $mountPath $kesKeyFile) "--shelley-vrf-key" (printf "%s/%s" $mountPath $vrfKeyFile) "--shelley-operational-certificate" (printf "%s/%s" $mountPath $opCertFile))) }}
          {{- end }}
          {{- if $args.all }}
          args:
            {{- range $args.all }}
            - {{ . | quote }}
            {{- end }}
          {{- end }}
          env:
            - name: CARDANO_NETWORK
              value: {{ .Values.node.network | quote }}
            - name: CARDANO_NODE_SOCKET_PATH
              value: {{ .Values.node.socketPath | quote }}
            {{- with .Values.node.networkMagic }}
            - name: CARDANO_NODE_NETWORK_ID
              value: {{ printf "%v" . | quote }}
            {{- end }}
            - name: RESTORE_SNAPSHOT
              value: "true"
            {{- with .Values.node.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.node.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: n2n
              containerPort: {{ .Values.service.n2nPort }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.service.metricsPort }}
              protocol: TCP
          volumeMounts:
            - name: chain-data
              mountPath: /data
            - name: ipc
              mountPath: /ipc
            {{- if $hasBlockProducerSecret }}
            - name: block-producer-keys
              mountPath: {{ default "/block-producer" $blockProducer.mountPath }}
              readOnly: true
            {{- end }}
            {{- if $configurationConfigMapName }}
            - name: configuration
              mountPath: {{ default "/configuration" .Values.configuration.mountPath }}
            {{- end }}
            {{- with .Values.node.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml (omit .Values.livenessProbe "enabled") | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml (omit .Values.readinessProbe "enabled") | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- if .Values.proxy.enabled }}
        - name: proxy
          image: "{{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}"
          imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
          {{- with .Values.proxy.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.proxy.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: n2c
              containerPort: {{ .Values.service.n2cPort }}
              protocol: TCP
          volumeMounts:
            - name: ipc
              mountPath: /ipc
            {{- if $proxyConfigName }}
            - name: proxy-config
              mountPath: /etc/nginx
            {{- end }}
            {{- with .Values.proxy.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.proxy.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.proxy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- end }}
        {{- with .Values.node.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: ipc
          emptyDir: {}
        {{- if $proxyConfigName }}
        - name: proxy-config
          configMap:
            name: {{ $proxyConfigName }}
        {{- end }}
        {{- if $configurationConfigMapName }}
        - name: configuration
          configMap:
            name: {{ $configurationConfigMapName }}
        {{- end }}
        {{- if $hasBlockProducerSecret }}
        - name: block-producer-keys
          secret:
            secretName: {{ $blockProducer.existingSecret }}
        {{- end }}
        {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: chain-data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- else if not .Values.persistence.enabled }}
        - name: chain-data
          emptyDir: {}
        {{- end }}
        {{- with .Values.node.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
  {{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: chain-data
        {{- with .Values.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{- end }}
