{{- $configName := include "dolos.configurationConfigMapName" . }}
{{- $root := . }}
{{- $contentDict := dict "value" "" }}
{{- if .Values.config.customConfig }}
{{- $_ := set $contentDict "value" (tpl .Values.config.customConfig $root) }}
{{- else }}
{{- $_ := set $contentDict "value" (include "dolos.configPreset" .) }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configName }}
  labels:
    {{- include "dolos.labels" . | nindent 4 }}
data:
  dolos.toml: |-
    {{- if $contentDict.value }}
    {{- $contentDict.value | nindent 4 }}
    {{- end }}
  {{- range $name, $template := .Values.config.extraFiles }}
  {{ $name }}: |-
    {{- tpl $template $root | nindent 4 }}
  {{- end }}
