{{- $fullName := include "dolos.fullname" . -}}
{{- $selectorLabels := include "dolos.selectorLabels" . -}}
{{- $serviceAccountName := include "dolos.serviceAccountName" . -}}
{{- $configMapName := include "dolos.configurationConfigMapName" . -}}
{{- $configChecksum := "" -}}
{{- if and .Values.config.create (not .Values.config.existingConfigMap) }}
{{- $configChecksum = include (print $.Template.BasePath "/configmap-config.yaml") . | sha256sum -}}
{{- end }}
{{- $configDir := default "/etc/config" .Values.config.mountPath -}}
{{- $configPath := printf "%s/%s" (trimSuffix "/" $configDir) .Values.config.filename -}}
{{- $dolosArgs := default (list "-c" $configPath "daemon") .Values.dolos.args -}}
{{- $bootstrapArgs := default (list "-c" $configPath "bootstrap" "snapshot" "--variant" "full") .Values.dolos.bootstrap.args -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "dolos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dolos.replicas | int }}
  selector:
    matchLabels:
{{- $selectorLabels | nindent 6 }}
  serviceName: {{ printf "%s-headless" $fullName }}
  template:
    metadata:
      labels:
{{- $selectorLabels | nindent 8 }}
      {{- $annotations := dict -}}
      {{- if $configChecksum }}
      {{- $_ := set $annotations "checksum/config" $configChecksum }}
      {{- end }}
      {{- with .Values.podAnnotations }}
      {{- range $key, $val := . }}
      {{- $_ := set $annotations $key $val }}
      {{- end }}
      {{- end }}
      {{- if gt (len $annotations) 0 }}
      annotations:
        {{- toYaml $annotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.dolos.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $hasInit := or (and .Values.dolos.bootstrap.enabled) (gt (len .Values.dolos.extraInitContainers) 0) }}
      {{- if $hasInit }}
      initContainers:
        {{- if .Values.dolos.bootstrap.enabled }}
        - name: {{ default "bootstrap" .Values.dolos.bootstrap.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.dolos.bootstrap.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $bootstrapArgs }}
          args:
            {{- toYaml $bootstrapArgs | nindent 12 }}
          {{- end }}
          {{- with .Values.dolos.bootstrap.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/data
            {{- if $configMapName }}
            - name: config
              mountPath: {{ $configDir }}
            {{- end }}
            {{- with .Values.dolos.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- end }}
        {{- with .Values.dolos.extraInitContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      containers:
        - name: dolos
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.dolos.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $dolosArgs }}
          args:
            {{- toYaml $dolosArgs | nindent 12 }}
          {{- end }}
          {{- with .Values.dolos.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.dolos.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.grpcPort }}
              protocol: TCP
            - name: ouroboros
              containerPort: {{ .Values.service.ouroborosPort }}
              protocol: TCP
            - name: minibf
              containerPort: {{ .Values.service.minibfPort }}
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/data
            {{- if $configMapName }}
            - name: config
              mountPath: {{ $configDir }}
            {{- end }}
            {{- with .Values.dolos.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml (omit .Values.livenessProbe "enabled") | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml (omit .Values.readinessProbe "enabled") | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- with .Values.dolos.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if $configMapName }}
        - name: config
          configMap:
            name: {{ $configMapName }}
        {{- end }}
        {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- else if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
        {{- end }}
        {{- with .Values.dolos.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
  {{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: data
        {{- with .Values.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{- end }}
