/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkloadIdRouteImport } from './routes/$workloadId'
import { Route as IndexRouteImport } from './routes/index'

const WorkloadIdRoute = WorkloadIdRouteImport.update({
  id: '/$workloadId',
  path: '/$workloadId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$workloadId': typeof WorkloadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$workloadId': typeof WorkloadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$workloadId': typeof WorkloadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$workloadId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$workloadId'
  id: '__root__' | '/' | '/$workloadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkloadIdRoute: typeof WorkloadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$workloadId': {
      id: '/$workloadId'
      path: '/$workloadId'
      fullPath: '/$workloadId'
      preLoaderRoute: typeof WorkloadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkloadIdRoute: WorkloadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
