{{- $fullName := include "cardano-db-sync.fullname" . -}}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ printf "%s-postgres" $fullName | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "cardano-db-sync.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ .Values.vaultAuth.ref | quote }}
  type: kv-v2
  mount: {{ .Values.credentials.vaultStaticSecret.mount | quote }}
  path: {{ required "credentials.vaultStaticSecret.path is required" .Values.credentials.vaultStaticSecret.path | quote }}
  refreshAfter: {{ .Values.credentials.vaultStaticSecret.refreshAfter | quote }}
  rolloutRestartTargets:
    - kind: StatefulSet
      name: {{ include "cardano-db-sync.postgresServiceName" . }}
    - kind: StatefulSet
      name: {{ $fullName }}
  destination:
    name: {{ include "cardano-db-sync.secretName" . | quote }}
    create: true
    overwrite: true
