apiVersion: v2
name: midnight
description: Helm chart to deploy Midnight on Supernode
type: application
version: 0.3.0
appVersion: "0.22.5"
keywords:
  - midnight
  - metis
  - supernode
annotations:
  displayName: Midnight Node
  icon: /images/workloads/midnight.svg
  category: partner-chain
  networkPath: node.network
