nameOverride: ""
fullnameOverride: ""
displayName: ""

image:
  repository: midnightnetwork/midnight-node
  tag: "0.22.5"

resources: {}

service:
  rpcPort: 9944
  p2pPort: 30333
  metricsPort: 9615

persistence:
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  annotations: {}
  size: 100Gi
  existingClaim: ""

node:
  replicas: 1
  network: preview
  cfgPreset: testnet-02
  bootnodes:
    - "/dns/bootnode-1.preview.midnight.network/tcp/30333/ws/p2p/12D3KooWK66i7dtGVNSwDh9tTeqov1q6LSdWsRLJvTyzTCaywYgK"
    - "/dns/bootnode-2.preview.midnight.network/tcp/30333/ws/p2p/12D3KooWHqFfXFwb7WW4jwR8pr4BEf562v5M6c8K3CXAJq4Wx6ym"
  pruning: ""
  extraArgs: []

vaultAuth:
  ref: control-plane/default
  serviceAccount:
    create: true
    name: vault-auth

dbSync:
  vaultStaticSecret:
    mount: kv
    path: ""
    refreshAfter: 1m

nodeKey:
  vaultStaticSecret:
    mount: kv
    path: ""
    refreshAfter: 1m

nodeSelector: {}
tolerations: []
affinity: {}
