/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as CatalogCategoryNodeIndexRouteImport } from './routes/catalog/$category/$node/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogCategoryNodeIndexRoute =
  CatalogCategoryNodeIndexRouteImport.update({
    id: '/catalog/$category/$node/',
    path: '/catalog/$category/$node/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/catalog/$category/$node': typeof CatalogCategoryNodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogIndexRoute
  '/catalog/$category/$node': typeof CatalogCategoryNodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog/': typeof CatalogIndexRoute
  '/catalog/$category/$node/': typeof CatalogCategoryNodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/catalog' | '/catalog/$category/$node'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalog' | '/catalog/$category/$node'
  id: '__root__' | '/' | '/catalog/' | '/catalog/$category/$node/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  CatalogCategoryNodeIndexRoute: typeof CatalogCategoryNodeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$category/$node/': {
      id: '/catalog/$category/$node/'
      path: '/catalog/$category/$node'
      fullPath: '/catalog/$category/$node'
      preLoaderRoute: typeof CatalogCategoryNodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  CatalogCategoryNodeIndexRoute: CatalogCategoryNodeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
