persistence:
  storageClass: standard

relayPersistence:
  storageClass: standard

node:
  network: vector-testnet

blockProducer:
  debug: true
  poolId: pool1exampleexampleexampleexampleexampleexampleexampleexample
  vaultStaticSecret:
    path: runtime/apex-fusion/example/block-producer
