dbSync:
  workload:
    releaseName: cardano-db-sync-preview
    namespace: preview
    postgresPort: 5432
  vaultStaticSecret:
    path: runtime/midnight/preview/dbsync
nodeKey:
  vaultStaticSecret:
    path: runtime/midnight/preview/node-key
persistence:
  storageClass: standard
