apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: o11y
    app.kubernetes.io/name: node-exporter
  name: node-exporter
  namespace: '{{ .Values.namespace }}'
spec:
  clusterIP: None
  ports:
  - name: https
    port: 9100
    targetPort: https
  selector:
    app.kubernetes.io/component: o11y
    app.kubernetes.io/name: node-exporter
