apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: '{{ .Values.namespace }}'
spec:
  type: NodePort
  selector:
    app.kubernetes.io/component: o11y
    app.kubernetes.io/name: grafana
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30000
    protocol: TCP
