apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-operator
  namespace: '{{ .Values.namespace }}'
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: 0.63.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: controller
        app.kubernetes.io/name: prometheus-operator
        app.kubernetes.io/version: 0.63.0
      annotations:
        kubectl.kubernetes.io/default-container: prometheus-operator
    spec:
      containers:
      - name: prometheus-operator
        image: quay.io/prometheus-operator/prometheus-operator:v0.63.0
        args:
        - --kubelet-service=kube-system/kubelet
        - --prometheus-config-reloader=quay.io/prometheus-operator/prometheus-config-reloader:v0.63.0
        ports:
        - name: http
          containerPort: 8080
{{- with .Values.prometheusOperator.resources }}
        resources:
{{ toYaml . | indent 10 }}
{{- end }}
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: prometheus-operator
      automountServiceAccountToken: true
      securityContext:
        runAsUser: 65534
        runAsNonRoot: true
{{- with .Values.prometheusOperator.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
{{- end }}
