apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-operator
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: 0.63.0
rules:
- verbs:
  - '*'
  apiGroups:
  - monitoring.coreos.com
  resources:
  - alertmanagers
  - alertmanagers/finalizers
  - alertmanagers/status
  - alertmanagerconfigs
  - prometheuses
  - prometheuses/finalizers
  - prometheuses/status
  - thanosrulers
  - thanosrulers/finalizers
  - servicemonitors
  - podmonitors
  - probes
  - prometheusrules
- verbs:
  - '*'
  apiGroups:
  - apps
  resources:
  - statefulsets
- verbs:
  - '*'
  apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
- verbs:
  - list
  - delete
  apiGroups:
  - ''
  resources:
  - pods
- verbs:
  - get
  - create
  - update
  - delete
  apiGroups:
  - ''
  resources:
  - services
  - services/finalizers
  - endpoints
- verbs:
  - list
  - watch
  apiGroups:
  - ''
  resources:
  - nodes
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - ''
  resources:
  - namespaces
- verbs:
  - get
  - list
  - watch
  apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
