{{- if .Values.vaultSecretsOperator.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vault-secrets-operator
  namespace: '{{ .Values.namespace }}'
  labels:
    app.kubernetes.io/component: o11y
    app.kubernetes.io/name: vault-secrets-operator
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/name: vault-secrets-operator
      app.kubernetes.io/instance: '{{ .Release.Name }}'
  namespaceSelector:
    matchNames:
    - '{{ .Values.namespace }}'
  endpoints:
  - port: https
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    scrapeTimeout: 10s
    path: /metrics
    params:
      format:
      - prometheus
    tlsConfig:
      insecureSkipVerify: true
{{- end }}
