apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: '{{ .Values.namespace }}'
spec:
  selector:
    app.kubernetes.io/component: o11y
    app.kubernetes.io/name: grafana
  ports:
  - port: 3000
    protocol: TCP
