apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator
  namespace: '{{ .Values.namespace }}'
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    app.kubernetes.io/version: 0.63.0
