{{- if and .Values.vault.integration.enabled .Values.vaultSecretsOperator.enabled .Values.vault.integration.auth.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: '{{ .Values.vault.integration.auth.serviceAccount.name }}'
  namespace: '{{ .Values.namespace }}'
  labels:
    app.kubernetes.io/component: o11y
    app.kubernetes.io/name: vault-auth
{{- end }}
