apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: '{{ .Values.namespace }}'
{{- $grafanaServiceType := default "ClusterIP" .Values.grafana.service.type }}
spec:
  type: {{ $grafanaServiceType }}
  selector:
    app.kubernetes.io/component: o11y
    app.kubernetes.io/name: grafana
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
{{- if and (eq $grafanaServiceType "NodePort") (not (empty .Values.grafana.service.nodePort)) }}
    nodePort: {{ .Values.grafana.service.nodePort }}
{{- end }}
