{{- if .Values.node.blockProducer.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "apex-fusion.blockProducerSecretName" . }}
  labels:
    {{- include "apex-fusion.labels" . | nindent 4 }}
spec:
  vaultAuthRef: {{ .Values.vaultAuth.ref | quote }}
  type: kv-v2
  mount: {{ .Values.node.blockProducer.vaultStaticSecret.mount | quote }}
  path: {{ .Values.node.blockProducer.vaultStaticSecret.path | quote }}
  refreshAfter: {{ .Values.node.blockProducer.vaultStaticSecret.refreshAfter | quote }}
  rolloutRestartTargets:
    - kind: StatefulSet
      name: {{ include "apex-fusion.fullname" . }}
  destination:
    name: {{ include "apex-fusion.blockProducerSecretName" . | quote }}
    create: true
    overwrite: true
{{- end }}
