apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "hydra-node.fullname" . }}
  labels:
    app.kubernetes.io/component: o11y
    {{- include "hydra-node.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
{{- include "hydra-node.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: monitoring
      path: /metrics
