{{- $secretName := include "hydra-node.hydraSigningSecretName" . }}
{{- if and $secretName (not .Values.keys.hydraSigning.existingSecret.name) .Values.keys.hydraSigning.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "hydra-node.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "hydra-node.hydraSigningSecretKey" . }}: {{ .Values.keys.hydraSigning.value | b64enc }}
{{- end }}
