{{- $fullName := include "hydra-node.fullname" . -}}
{{- $selectorLabels := include "hydra-node.selectorLabels" . -}}
{{- $serviceAccountName := include "hydra-node.serviceAccountName" . -}}
{{- $protocolConfigName := include "hydra-node.protocolParametersConfigMapName" . -}}
{{- $initialUtxoConfigName := include "hydra-node.initialUtxoConfigMapName" . -}}
{{- $hydraSigningSecretName := required "You must provide a Hydra signing key via keys.hydraSigning.value or keys.hydraSigning.existingSecret.name" (include "hydra-node.hydraSigningSecretName" .) -}}
{{- $hydraSigningSecretKey := include "hydra-node.hydraSigningSecretKey" . -}}
{{- $hydraVerificationConfigName := include "hydra-node.hydraVerificationConfigMapName" . -}}
{{- $verificationCount := 0 -}}
{{- range $item := .Values.keys.hydraVerification.items }}
  {{- if $item.filename }}
    {{- $verificationCount = add $verificationCount 1 }}
  {{- end }}
{{- end }}
{{- if lt $verificationCount 1 }}
  {{- fail "At least one Hydra verification key filename must be listed in keys.hydraVerification.items" }}
{{- end }}
{{- $cardanoEnabled := .Values.keys.cardano.enabled -}}
{{- if and (not .Values.node.offlineMode) (not $cardanoEnabled) }}
{{- fail "Online mode requires keys.cardano.enabled=true along with Cardano keys and socket mounts" }}
{{- end }}
{{- $cardanoSigningSecretName := "" -}}
{{- $cardanoSigningSecretKey := "" -}}
{{- $cardanoVerificationConfigName := "" -}}
{{- if $cardanoEnabled }}
  {{- $cardanoSigningSecretName = required "Cardano signing key must be provided when keys.cardano.enabled=true" (include "hydra-node.cardanoSigningSecretName" .) }}
  {{- $cardanoSigningSecretKey = include "hydra-node.cardanoSigningSecretKey" . }}
  {{- $cardanoVerificationConfigName = include "hydra-node.cardanoVerificationConfigMapName" . }}
  {{- if not $cardanoVerificationConfigName }}
    {{- fail "Cardano verification key must be provided via keys.cardano.verification when keys.cardano.enabled=true" }}
  {{- end }}
{{- end }}
{{- $protocolChecksum := "" -}}
{{- if and .Values.ledger.protocolParameters.create (not .Values.ledger.protocolParameters.name) }}
  {{- $protocolChecksum = include (print $.Template.BasePath "/configmap-protocol-parameters.yaml") . | sha256sum }}
{{- end }}
{{- $initialUtxoChecksum := "" -}}
{{- if and .Values.ledger.initialUtxo.create (not .Values.ledger.initialUtxo.name) }}
  {{- $initialUtxoChecksum = include (print $.Template.BasePath "/configmap-initial-utxo.yaml") . | sha256sum }}
{{- end }}
{{- $verificationChecksum := "" -}}
{{- if and (gt (len (default (list) .Values.keys.hydraVerification.items)) 0) (not .Values.keys.hydraVerification.existingConfigMap.name) }}
  {{- $verificationChecksum = include (print $.Template.BasePath "/configmap-hydra-verification.yaml") . | sha256sum }}
{{- end }}
{{- $cardanoVerificationChecksum := "" -}}
{{- if and $cardanoEnabled (not .Values.keys.cardano.verification.existingConfigMap.name) .Values.keys.cardano.verification.value }}
  {{- $cardanoVerificationChecksum = include (print $.Template.BasePath "/configmap-cardano-verification.yaml") . | sha256sum }}
{{- end }}
{{- $args := .Values.node.args -}}
{{- if not $args }}
  {{- $args = list }}
  {{- $ledgerMount := trimSuffix "/" .Values.ledger.mountPath }}
  {{- $keysMount := trimSuffix "/" .Values.keys.mountPath }}
  {{- $persistenceDir := .Values.persistence.mountPath | default "/var/lib/hydra" }}
  {{- $hydraSigningPath := printf "%s/%s" $keysMount (default "hydra.sk" .Values.keys.hydraSigning.filename) }}
  {{- if .Values.node.offlineMode }}
    {{- if not $protocolConfigName }}
      {{- fail "Offline mode requires ledger.protocolParameters to be configured or provided via existing ConfigMap" }}
    {{- end }}
    {{- if not $initialUtxoConfigName }}
      {{- fail "Offline mode requires ledger.initialUtxo to be configured or provided via existing ConfigMap" }}
    {{- end }}
    {{- $args = append $args "offline" }}
    {{- $args = append $args "--initial-utxo" }}
    {{- $args = append $args (printf "%s/%s" $ledgerMount .Values.ledger.initialUtxo.filename) }}
    {{- $args = append $args "--ledger-protocol-parameters" }}
    {{- $args = append $args (printf "%s/%s" $ledgerMount .Values.ledger.protocolParameters.filename) }}
  {{- else }}
    {{- $args = append $args "--node-id" }}
    {{- $args = append $args .Values.node.nodeId }}
    {{- $args = append $args "--hydra-scripts-tx-id" }}
    {{- $args = append $args (required "node.hydraScriptsTxId must be set when running online" .Values.node.hydraScriptsTxId) }}
    {{- $args = append $args "--cardano-signing-key" }}
    {{- $args = append $args (printf "%s/%s" $keysMount (default "cardano.sk" .Values.keys.cardano.signing.filename)) }}
    {{- $args = append $args "--cardano-verification-key" }}
    {{- $args = append $args (printf "%s/%s" $keysMount (default "cardano.vk" .Values.keys.cardano.verification.filename)) }}
    {{- $args = append $args "--node-socket" }}
    {{- $args = append $args .Values.keys.cardano.socketPath }}
  {{- end }}
  {{- $args = append $args "--hydra-signing-key" }}
  {{- $args = append $args $hydraSigningPath }}
  {{- range $item := .Values.keys.hydraVerification.items }}
    {{- if $item.filename }}
      {{- $args = append $args "--hydra-verification-key" }}
      {{- $args = append $args (printf "%s/%s" $keysMount $item.filename) }}
    {{- end }}
  {{- end }}
  {{- $args = append $args "--host" }}
  {{- $args = append $args (printf "%v" .Values.node.host) }}
  {{- $args = append $args "--port" }}
  {{- $args = append $args (printf "%v" .Values.service.p2pPort) }}
  {{- $args = append $args "--api-host" }}
  {{- $args = append $args (printf "%v" .Values.node.apiHost) }}
  {{- $args = append $args "--api-port" }}
  {{- $args = append $args (printf "%v" .Values.service.apiPort) }}
  {{- $args = append $args "--monitoring-port" }}
  {{- $args = append $args (printf "%v" .Values.service.monitoringPort) }}
  {{- $args = append $args "--persistence-dir" }}
  {{- $args = append $args $persistenceDir }}
  {{- if .Values.node.quiet }}
    {{- $args = append $args "--quiet" }}
  {{- end }}
  {{- range $extra := .Values.node.extraArgs }}
    {{- $args = append $args $extra }}
  {{- end }}
{{- end }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "hydra-node.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.node.replicas | int }}
  selector:
    matchLabels:
{{- $selectorLabels | nindent 6 }}
  serviceName: {{ printf "%s-headless" $fullName }}
  template:
    metadata:
      labels:
{{- $selectorLabels | nindent 8 }}
      {{- $annotations := dict -}}
      {{- if $protocolChecksum }}
      {{- $_ := set $annotations "checksum/protocol-parameters" $protocolChecksum }}
      {{- end }}
      {{- if $initialUtxoChecksum }}
      {{- $_ := set $annotations "checksum/initial-utxo" $initialUtxoChecksum }}
      {{- end }}
      {{- if $verificationChecksum }}
      {{- $_ := set $annotations "checksum/hydra-verification" $verificationChecksum }}
      {{- end }}
      {{- if $cardanoVerificationChecksum }}
      {{- $_ := set $annotations "checksum/cardano-verification" $cardanoVerificationChecksum }}
      {{- end }}
      {{- with .Values.podAnnotations }}
      {{- range $key, $val := . }}
      {{- $_ := set $annotations $key $val }}
      {{- end }}
      {{- end }}
      {{- if gt (len $annotations) 0 }}
      annotations:
        {{- toYaml $annotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ $serviceAccountName }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.node.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.node.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: hydra-node
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.node.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $args }}
          args:
            {{- toYaml $args | nindent 12 }}
          {{- end }}
          {{- with .Values.node.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.node.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: api
              containerPort: {{ .Values.service.apiPort }}
              protocol: TCP
            - name: p2p
              containerPort: {{ .Values.service.p2pPort }}
              protocol: TCP
            - name: monitoring
              containerPort: {{ .Values.service.monitoringPort }}
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: {{ .Values.persistence.mountPath | default "/var/lib/hydra" }}
              {{- with .Values.node.persistenceSubPath }}
              subPath: {{ . }}
              {{- end }}
            - name: keys
              mountPath: {{ .Values.keys.mountPath | default "/etc/keys" }}
            {{- if or $protocolConfigName $initialUtxoConfigName }}
            - name: ledger-config
              mountPath: {{ .Values.ledger.mountPath | default "/etc/hydra" }}
            {{- end }}
            {{- with .Values.node.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml (omit .Values.livenessProbe "enabled") | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml (omit .Values.readinessProbe "enabled") | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- with .Values.node.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        {{- with .Values.node.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: keys
          projected:
            sources:
              - secret:
                  name: {{ $hydraSigningSecretName }}
                  items:
                    - key: {{ $hydraSigningSecretKey }}
                      path: {{ default "hydra.sk" .Values.keys.hydraSigning.filename }}
              {{- if $hydraVerificationConfigName }}
              - configMap:
                  name: {{ $hydraVerificationConfigName }}
              {{- end }}
              {{- if $cardanoEnabled }}
              - secret:
                  name: {{ $cardanoSigningSecretName }}
                  items:
                    - key: {{ $cardanoSigningSecretKey }}
                      path: {{ default "cardano.sk" .Values.keys.cardano.signing.filename }}
              {{- if $cardanoVerificationConfigName }}
              - configMap:
                  name: {{ $cardanoVerificationConfigName }}
              {{- end }}
              {{- end }}
        {{- if or $protocolConfigName $initialUtxoConfigName }}
        - name: ledger-config
          projected:
            sources:
              {{- if $protocolConfigName }}
              - configMap:
                  name: {{ $protocolConfigName }}
                  items:
                    - key: {{ .Values.ledger.protocolParameters.filename }}
                      path: {{ .Values.ledger.protocolParameters.filename }}
              {{- end }}
              {{- if $initialUtxoConfigName }}
              - configMap:
                  name: {{ $initialUtxoConfigName }}
                  items:
                    - key: {{ .Values.ledger.initialUtxo.filename }}
                      path: {{ .Values.ledger.initialUtxo.filename }}
              {{- end }}
        {{- end }}
        {{- if and (not .Values.persistence.enabled) (not .Values.persistence.existingClaim) }}
        - name: data
          emptyDir: {}
        {{- else if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: data
        {{- with .Values.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{- end }}
