persistence:
  storageClass: standard

keys:
  hydraSigning:
    vaultStaticSecret:
      path: runtime/hydra/hydra-signing
  hydraVerification:
    existingConfigMap:
      name: hydra-verification
    items:
      - filename: hydra.vk
