keys:
  hydraSigning:
    vaultStaticSecret:
      enabled: true
      path: hydra/hydra-signing
  hydraVerification:
    existingConfigMap:
      name: hydra-verification
    items:
      - filename: hydra.vk
