keys:
  hydraSigning:
    vaultStaticSecret:
      path: runtime/hydra/offline/hydra-signing
  hydraVerification:
    items:
      - filename: hydra.vk
        value: |-
          offline-hydra-verification-key
