{{- $fullName := include "midnight.fullname" . -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app.kubernetes.io/component: o11y
  name: {{ $fullName }}
spec:
  podMetricsEndpoints:
  - path: /metrics
    port: metrics
  selector:
    matchLabels:
      {{- include "midnight.selectorLabels" . | nindent 6 }}
