{{- if and .Values.dbSync.managed.enabled (not .Values.dbSync.managed.connection.existingSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "midnight.dbSyncPostgresSecretName" . }}
  labels:
    {{- include "midnight.labels" . | nindent 4 }}
    app.kubernetes.io/component: dbsync-postgres
type: Opaque
stringData:
  username: {{ required ".Values.dbSync.managed.connection.username is required when managed dbSync is enabled without an existing secret" .Values.dbSync.managed.connection.username }}
  password: {{ required ".Values.dbSync.managed.connection.password is required when managed dbSync is enabled without an existing secret" .Values.dbSync.managed.connection.password }}
  database: {{ required ".Values.dbSync.managed.connection.database is required when managed dbSync is enabled without an existing secret" .Values.dbSync.managed.connection.database }}
{{- end }}
