{{- $secretName := include "midnight.nodeKeySecretName" . }}
{{- if and $secretName (not .Values.nodeKey.existingSecret.name) .Values.nodeKey.value }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "midnight.labels" . | nindent 4 }}
type: Opaque
data:
  {{ include "midnight.nodeKeySecretKey" . }}: {{ .Values.nodeKey.value | b64enc }}
{{- end }}
