apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "midnight.fullname" .) }}
  labels:
    {{- include "midnight.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
{{- include "midnight.selectorLabels" . | nindent 4 }}
