{{- if .Values.vaultAuth.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.vaultAuth.serviceAccount.name | quote }}
  labels:
    {{- include "midnight.labels" . | nindent 4 }}
{{- end }}
