{{- $fullName := include "midnight.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "midnight.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
{{- include "midnight.selectorLabels" . | nindent 4 }}
  ports:
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
