{{- if and .Values.vaultAuth.serviceAccount.create (or .Values.nodeKey.vaultStaticSecret.enabled .Values.dbSync.vaultStaticSecret.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.vaultAuth.serviceAccount.name | quote }}
  labels:
    {{- include "midnight.labels" . | nindent 4 }}
{{- end }}
