nameOverride: ""
fullnameOverride: ""
displayName: ""

image:
  repository: ghcr.io/txpipe/dolos
  tag: "v1.1.1"

resources:
  requests:
    cpu: 500m
    memory: 4Gi
  limits:
    cpu: "2"
    memory: 4Gi

service:
  type: ClusterIP
  annotations: {}
  labels: {}
  clusterIP: ""
  loadBalancerIP: ""
  externalTrafficPolicy: ""
  grpcPort: 50051
  grpcNodePort: null
  ouroborosPort: 30013
  ouroborosNodePort: null
  minibfPort: 3001
  minibfNodePort: null
  minikupoPort: 1442
  minikupoNodePort: null
  trpPort: 8164
  trpNodePort: null

persistence:
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  annotations: {}
  size: 20Gi
  existingClaim: ""

dolos:
  replicas: 1
  network: cardano-preview
  command: []
  args:
    - "-c"
    - "/etc/config/dolos.toml"
    - "daemon"
  bootstrap:
    enabled: true
    name: bootstrap
    command: []
    args: []

config:
  customConfig: ""
  # Must point to a trusted Cardano relay used for syncing.
  upstreamAddress: ""
  extraFiles: {}

nodeSelector: {}
tolerations: []
affinity: {}
topologySpreadConstraints: []
