name: Build frontend

on:
  push:
    branches:
      - "main"
    paths:
      - "frontend/Dockerfile"
      - ".github/workflows/build_frontend.yml"
      - "frontend/**"

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Add docker layer caching to avoid doing extra computation
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: frontend
          file: frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/txpipe/metis-frontend,ghcr.io/txpipe/metis-frontend:${{ github.sha }}
