name: Check backend

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/check_backend.yml"
      - "backend/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/check_backend.yml"
      - "backend/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clippy check lints
        run: cargo clippy -- -D warnings
