name: Test operator

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test_operator.yml"
      - "operator/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/test_operator.yml"
      - "operator/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./operator
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: cargo test
