name: Test CLI

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test_cli.yml"
      - "cli/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/test_cli.yml"
      - "cli/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: cargo test
