name: Test backend

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test_backend.yml"
      - "backend/**"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/test_backend.yml"
      - "backend/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: cargo test
